### ISSUE TITLE
Move App from Bootstrap to Bulma

### ISSUE THREAD

**Issue by Deng78** [jloh/geojs-app#11]
Similar to Issue #7 

It would be nice to have the UI of the App similar to the www.geojs.io website.

**Comment by Deng78** [comment]
Created a branch on my fork for this issue.

https://github.com/Deng78/geojs-app/tree/ui_update

**Comment by jloh** [comment]
Would definitely look at merging this for sure! Bulma or a port to tailwind would be perfect!

**Comment by jloh** [comment]
Migrated to Tailwind as part of the SvelteKit port.
